from __future__ import annotations

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "Appliances": ["appliance", "refrigerator", "washer", "dryer", "dishwasher"],
    "Architecture and Design": ["architect", "architectural", "design-build", "design build", "engineering design"],
    "Asphalt": ["asphalt", "paving", "mill and overlay", "seal coat"],
    "Basement": ["basement", "foundation waterproofing", "sump pump"],
    "Bathroom": ["bathroom", "restroom", "shower", "toilet partition"],
    "Cabinets": ["cabinet", "millwork", "casework"],
    "Carpentry / Glaziery": ["carpentry", "glazing", "glass", "storefront", "framing"],
    "Carpeting": ["carpet", "broadloom", "tile carpet", "floor covering"],
    "Concrete": ["concrete", "sidewalk", "curb", "slab"],
    "Decks and Porches": ["deck", "porch", "railing"],
    "Electrical": ["electrical", "electrician", "lighting", "generator", "switchgear", "signal", "power distribution", "wiring"],
    "Equipment Rental": ["equipment rental", "rental equipment", "lift rental", "heavy equipment"],
    "Excavating": ["excavation", "excavating", "earthwork", "trenching", "grading"],
    "Exterior Cleaning": ["pressure washing", "exterior cleaning", "facade cleaning"],
    "Exterior Installation": ["canopy", "awning", "exterior install", "site installation"],
    "Exterior Maintenance": ["exterior maintenance", "site maintenance", "grounds maintenance"],
    "Fencing": ["fence", "gates", "perimeter fencing"],
    "Flooring": ["flooring", "tile", "vct", "luxury vinyl", "epoxy floor"],
    "Garage": ["garage", "overhead door", "parking structure"],
    "Gas": ["gas line", "natural gas", "propane"],
    "Generators": ["generator", "backup power", "standby generator"],
    "HVAC": ["hvac", "boiler", "chiller", "air handler", "air conditioning", "ventilation", "duct", "filter", "mechanical"],
    "Hearth and Chimney": ["chimney", "hearth", "flue"],
    "Interior Cleaning": ["janitorial", "custodial", "interior cleaning", "floor cleaning"],
    "Interior Decoration": ["interior decoration", "window treatment", "furnishing"],
    "Interior Installation": ["interior installation", "fixture installation", "tenant finish-out"],
    "Interior Maintenance": ["interior maintenance", "building maintenance", "facility maintenance"],
    "Lawn and Landscaping": ["landscaping", "landscape", "lawn", "irrigation", "groundskeeping", "tree trimming"],
    "Life Safety": ["life safety", "fire alarm", "sprinkler", "fire protection"],
    "Metalwork": ["metalwork", "steel fabrication", "welding", "ornamental iron"],
    "Moving": ["moving", "relocation", "furniture moving"],
    "Paint": ["paint", "painting", "coating", "striping"],
    "Plaster": ["plaster", "stucco", "drywall finish"],
    "Plumbing": ["plumbing", "plumber", "water line", "sewer", "drain", "backflow", "pipe"],
    "Roofing": ["roof", "roofing", "reroof", "membrane", "flashing"],
    "Security": ["security", "cctv", "access control", "surveillance"],
    "Structural Work": ["structural", "bridge", "rehabilitation", "steel repair", "load bearing"],
    "Surveys and Appraisal": ["survey", "appraisal", "land survey", "valuation"],
    "Wall-Making": ["masonry", "wall", "retaining wall", "partition"],
    "Wallpaper": ["wallpaper", "wall covering"],
    "Waste Management": ["waste", "trash", "refuse", "disposal", "recycling", "solid waste", "wastewater"],
    "Windows": ["window", "glazing", "storefront glass"],
    "General Contractors": ["general contractor", "construction contract", "construction", "rehabilitation", "renovation", "improvement project"],
    "Gutters": ["gutter", "downspout"],
    "Hazard Abatement": ["abatement", "asbestos", "lead", "hazmat", "hazardous material"],
    "Insulation": ["insulation", "spray foam", "thermal barrier"],
}

NEGATIVE_KEYWORDS = {
    "software",
    "saas",
    "cybersecurity",
    "insurance",
    "actuarial",
    "legal",
    "attorney",
    "medical",
    "pharmaceutical",
    "vaccine",
    "point of sale",
}

